# Site settings
title: Ben Burton's Blog
email: benjamin.joseph.burton@gmail.com
description: ""
baseurl: ""
url: "http://benburton.github.io/"
twitter_username: bjburton
github_username:  benburton

# Build settings
markdown: kramdown
permalink: pretty
plugins:     ./_plugins